/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.security.PrivateKey;
import java.security.PublicKey;

import org.junit.Test;

public class AppTest {
	@Test
	public void testAppHasAGreeting() throws Exception {
		final String text = "1234567890";
		String privateKeyString = "MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAJ6TA4P1NTkeWw3Hls6oPKXUgULysO+ntDllUyTLzR8wN1jLEEDQzwWinu+shS8XxeJjGeLns2tp4OAcO50R8gRfkYIC7NHshYLKMSypl/r1Tb2BMjGo3xnEi0/dxgH7fIC28oN4TfQvOLQvHOapCIRz1i+vFVYaGOusr5m99QwNAgMBAAECgYBWcq8n8TXivbnF+VktsGnfvcn6RXRQMoz9/U8mcDSTHCYQMiPaMfuqhs0+vD6fPcaTdJNYMBiQJliB1OJq7q2Q+Pxv9/S0c5VrxAeBiOOeQgWAEX1aOEhEZOm7ONnJL+78/N9lCuRWJ0HOKV6n8u5pijsFjWubyVsFGbHFDDOeAQJBANAihxpZE/ewwa1RliNAqZ31i9PST/rUStmOMcHQzwMQspKmAzvDfm+9YmWoSfPTQgvprn8w6wGB/hYHA5cr3tUCQQDDCreUvSd77PLqSr2AOmBRszTWUiev29P7gsqhQLwhLQCdY4fYC6f+XT5yWVFCv25ArtPmSFJperyaDHNQdERZAkBLulRXxNNcCqbdTdMHro5IV7/xaRMKm1VEhNUbxMKdReUDMH36r62AMHLts+Z8XYApX3PK+Vx4JvjwwMqQpTilAkBwyJy51NulLLKXStrj8F3MQK2YFW+/oIWnVc1oi69+G7DUUj62bp8ZVsAKjZ2Q1HOj0bTU4BNPzVqMVhDEgEcZAkAugh4rvNuspzAaby0vpMlBiINzlg+ZgkOvITyjy6Zi7uncs+Bvg6FOB7SxnqRR0XSkKFxNol1ir4BSvw9W/646";
		String publicKeyString = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCekwOD9TU5HlsNx5bOqDyl1IFC8rDvp7Q5ZVMky80fMDdYyxBA0M8Fop7vrIUvF8XiYxni57NraeDgHDudEfIEX5GCAuzR7IWCyjEsqZf69U29gTIxqN8ZxItP3cYB+3yAtvKDeE30Lzi0LxzmqQiEc9YvrxVWGhjrrK+ZvfUMDQIDAQAB";
		PrivateKey privateKey = SignUtil.privateKey(privateKeyString);
		assertNotNull(privateKey);
		PublicKey publicKey = SignUtil.publicKey(publicKeyString);
		assertNotNull(publicKey);
		String signed = SignUtil.sign(text, privateKey);
		assertNotNull(signed);
		assertTrue(SignUtil.verify(text, signed, publicKey));
	}
}
